app1/urls.py
from django.urls import path
from . import views
from .views import PostView


app_name='app1'

urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('contact/', views.contact, name='contact'),
# Dynamic url
    path('icd/<slug:slugID>', views.iceCreamDetails, name='Ice_cream_details'),
    path('cartProduct/', views.cartProduct, name='cartProduct'),
    path('checkOut/', views.checkOut, name='checkOut'),
      
# API url to GET data using function based View
    path('api/get/', views.get_all_IceCreams, name='get_api'),
    path('api/get/<int:id>', views.get_all_IceCreams, name='get_api_id'),
# API url to POST data using Class based View
    path('api/post/', PostView.as_view(), name='post_api'),
    
]


icecream/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


# Added Manually for changing heading inside /admin page of django
admin.site.site_header = "Ice Cream Admin"
admin.site.site_title = "Ice Cream Admin Portal"
admin.site.index_title = "Welcome to Ice Cream Researcher Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('users/',include('users.urls'))
]


urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends 'base.html' %}

{% block content %}



<div class="bg-light">
  <div class="container py-5">
    <div class="row h-100 align-items-center py-5">
      <div class="col-lg-6">
        <h1 class="display-4">About Us </h1>
        <p class="lead text-muted mb-0" style="font-size:18px">We are here to provide you the best IceCream.</p>
        <p class="lead text-muted mb-0" style="font-size:18px">You can access data using REST API by going to <span style="color:red"> /api/get/ </span></p>
{% comment %} 
        <p class="lead text-muted">Snippet by <a href="https://bootstrapious.com/snippets" class="text-muted"> 
                    <u>Bootstrapious</u></a>
        </p> 
{% endcomment %}
      </div>
      <div class="col-lg-6 d-none d-lg-block"><img src="https://bootstrapious.com/i/snippets/sn-about/illus.png" alt="" class="img-fluid"></div>
    </div>
  </div>
</div>

<div class="bg-white py-5">
  <div class="container py-5">
{% comment %} 
      <div class="row align-items-center mb-5">
      <div class="col-lg-6 order-2 order-lg-1"><i class="fa fa-bar-chart fa-2x mb-3 text-primary"></i>
        <h2 class="font-weight-light">Lorem ipsum dolor sit amet</h2>
        <p class="font-italic text-muted mb-4" style="font-size:18px">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><a href="#" class="btn btn-light px-5 rounded-pill shadow-sm">Learn More</a>
      </div>
      <div class="col-lg-5 px-5 mx-auto order-1 order-lg-2"><img src="https://bootstrapious.com/i/snippets/sn-about/img-1.jpg" alt="" class="img-fluid mb-4 mb-lg-0"></div>
    </div> 
{% endcomment %}
    <div class="row align-items-center">
      <div class="col-lg-5 px-5 mx-auto"><img src="https://bootstrapious.com/i/snippets/sn-about/img-2.jpg" alt="" class="img-fluid mb-4 mb-lg-0"></div>
      <div class="col-lg-6"><i class="fa fa-leaf fa-2x mb-3 text-primary"></i>
        <h2 class="font-weight-light">Origin</h2>
        <p class="font-italic text-muted mb-4" style="font-size:18px">We are serving IceCream to people since 1998 and came online after 2013. Customers have trusted us over 2 dacade and we want to keep this continue.</p><a href="#" class="btn btn-light px-5 rounded-pill shadow-sm">Learn More</a>
      </div>
    </div>
  </div>
</div>

<div class="bg-light ">
  <div class="container">
    <div class="row mb-4">
      <div class="col-lg-5">
        <h2 class="display-4 font-weight-light">Our team</h2>
        <p class="font-italic text-muted">Three People behind this business</p>
      </div>
    </div>

    <div class="row text-center lx-center" >


      <!-- Team item-->
      <div class="col-xl-3 col-sm-6 mb-5 " style="display:inline-block; margin:0 auto;">
        <div class="bg-white rounded shadow-sm py-5 px-4"><img src="https://bootstrapious.com/i/snippets/sn-about/avatar-3.png" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
          <a href='http://github.com/iash8090' target='_blank'>
          <h5 class="mb-0">Ashish Sharma</h5> </a><span class="small text-uppercase text-muted">CEO - Founder</span>
          <ul class="social mb-0 list-inline mt-3">
            <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-facebook-f"></i></a></li>
            <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-twitter"></i></a></li>
            <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-instagram"></i></a></li>
            <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-linkedin"></i></a></li>
          </ul>
        </div>
      </div>
      <!-- End-->


      <!-- Team item-->
      <div class="col-xl-3 col-sm-6 mb-5"  style="display:inline-block; margin:0 auto;">
        <div class="bg-white rounded shadow-sm py-5 px-4"><img src="https://bootstrapious.com/i/snippets/sn-about/avatar-2.png" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
          <h5 class="mb-0">Tom Sunderland</h5><span class="small text-uppercase text-muted">CO - Founder</span>
          <ul class="social mb-0 list-inline mt-3">
            <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-facebook-f"></i></a></li>
            <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-twitter"></i></a></li>
            <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-instagram"></i></a></li>
            <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-linkedin"></i></a></li>
          </ul>
        </div>
      </div>
      <!-- End-->

      <!-- Team item-->
      <div class="col-xl-3 col-sm-6 mb-5"  style="display:inline-block; margin:0 auto;">
        <div class="bg-white rounded shadow-sm py-5 px-4"><img src="https://bootstrapious.com/i/snippets/sn-about/avatar-1.png" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
          <h5 class="mb-0">John Tarly</h5><span class="small text-uppercase text-muted">CO - Founder</span>
          <ul class="social mb-0 list-inline mt-3">
            <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-facebook-f"></i></a></li>
            <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-twitter"></i></a></li>
            <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-instagram"></i></a></li>
            <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-linkedin"></i></a></li>
          </ul>
        </div>
      </div>
      <!-- End-->

    </div>
  </div>
</div>


<footer class="bg-light pb-5">
  <div class="container text-center">
    <p class="font-italic text-muted mb-0">&copy; Copyrights IceCream.com &nbsp; All rights reserved.</p>
  </div>
  <div class="container text-center">
    <p class="font-italic text-muted mb-0"> 2023</p>
  </div>
</footer>

{% endblock content %}


{% block title %}
About
{% endblock title %}




templates/base.html
<!doctype html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static '/css/base.css' %}"> 

    
  </head>    
  <body>
    <div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">IceCreams</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link " aria-current="page" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/about">About Us</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Services
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item disabled" href="/services">Cone</a></li>
                  <li><a class="dropdown-item disabled" href="/services">Softy</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="/services">Family Pack</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="/contact">Contact Us</a>
              </li>
            </ul>
            {% url 'app1:home' as home_url %}
            {% if request.path == home_url %}
            <form class="d-flex" method="GET" >
              <input class="form-control" name ="search_iceCream" type="search" value="{{srch_iceCream}}" placeholder="Search" aria-label="Search"/>
              <button class="btn btn-outline-success mx-3" type="submit">Search</button>
            </form>
            {% endif %}
          
          
            {% if request.user.is_authenticated %}
            <div>
              <a class="nav-link" href="/cartProduct" >
                  <button class="btn btn-outline-success mx-2" style="position: relative; color:red;"  type="button"> <i class="fa fa-shopping-cart"></i> 
                    (<span id="cartcount">0 <script>
                      if (sessionStorage.getItem('cart') == null) {
                        var cart = {};
                    }
                    else {
                        cart = JSON.parse(sessionStorage.getItem('cart'));
                        document.getElementById('cartcount').innerHTML = Object.keys(cart).length;
                    }
                   </script> </span>) 
                  </button>
                  </a>
              </div>
            {% endif %}


            {% if request.user.is_authenticated %}
            {% with x="Logout" %}
            <div>
            <a class="nav-link" href="/users/logout" >
                <button class="btn btn-outline-success" style="position: relative;"  type="submit"> {{x}}</button>
                </a>
            </div>
            {% endwith %}
            {% else %}
            {% with x="Login" %}
            <div>
            <a class="nav-link" href="/users/login" >
                <button class="btn btn-outline-success" style="position: relative;  right:10px" type="submit"> {{x}}</button>
                </a>
            </div>
            {% endwith %}
            {% endif %}
          </div>
        </div>
      </nav>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="{% static '/js/cartProduct.js' %}"> </script>
    {% block js %}   {% endblock js %}


{% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{message.tags}} alert-dismissible fade show my-0" role="alert">
    <strong>{{message}}</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
{% endif %}

    {% block content %}
    {% endblock content %}

    <title>
    {% block title %}
    {% endblock title %}
    </title>

</body>
</html>

templates/cartProduct.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static '/css/cartProduct.css' %}">


<div class="container px-4 py-5 mx-auto ">
    <div class="row d-flex justify-content-center">
        <div class="col-5">
            <h4 class="heading">Shopping Bag</h4>
        </div>
        <div class="col-7">
            <div class="row d-flex text-right">
                <div class="col-3">
                    <h6 class="mt-2">Price</h6>
                </div>
                <div class="col-3">
                    <h6 class="mt-2">Quantity</h6>
                </div>
                <div class="col-3">
                    <h6 class="mt-2">Total Price</h6>
                </div>
                <div class="col-3">
                    <h6 class="mt-2"> Remove Item </h6>
                </div>
            </div>
        </div>
    </div>
    <div id="items" >
        </div>
    <div class="row justify-content-center">
        <div class="col-lg-12">
            <div class="card align-center">
                <div class="row">
                    <div class="col">
                        <div class="d-flex justify-content-between align-items-center">
                            <div>
                                <button class="btn btn-sm bg-light border border-dark" onclick="history.back()">GO BACK</button>
                            </div>
                            <div style="font-size:120%; margin-right: 5%; margin-left: 5%;"><b><u>Total Amount</u> - ₹ <span id="tAmount"> </b> </span>
                                <h6 class="mb-1 align-center" style="font-size:120%"></h6>
                            </div>
                            <div>
                                <button class="btn btn-primary" onclick="window.location.href='/checkOut'">
                                    <span id="checkout">Checkout</span>   
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% block js %}
<script src="{% static '/js/cart.js' %}">
</script>

{% endblock js %}

{% endblock content %}

{% block title %}
Cart Items  
{% endblock title %}

templates/checkOut.html
{% extends 'base.html' %}

{% block content %}

<style>
.box{
    display:flex;
    align-items: center;
    justify-content: center;
    width:100%;
    height:100px;
}
</style>

<div class="box">
<h1 > Your Ice Creams are on the way</h1> </div>
<div class="box"><h1  > 👍  </h1></div>
<div class="box"><h1>  Free of Cost, Enjoy! </h1></div>
</div>


{% endblock content %}

{% block title %}
Check Out
{% endblock title %}

templates/contact.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid px-0" style="width:100%">
<img src="/static/img/contact-us-image.jpg" class="d-block w-100 p-2"  width="1300" height="500">
</div>

<div class="container-fluid py-4 " style="width:100%">
    <div class="row" >
  <div class="mx-auto col-10 col-md-8 col-lg-6">
    <form method="post" action="/contact/">
        {% csrf_token %}
    <div class="mb-3">
  <label for="name" class="form-label"><b>Name</b></label>
  <input type="text" class="form-control" style="width:100%; border:1px solid black" id="name" name="name" value='{{request.user.username}}' placeholder="Enter Username" required>
</div>
    <div class="mb-3">
  <label for="email" class="form-label"><b>Email address</b></label>
  <input type="email" class="form-control" style="width:100%; border:1px solid black " id="email" name="email" value='{{request.user.email}}' placeholder="Enter Email" required>
</div>
    <div class="mb-3">
  <label for="phone" class="form-label"><b>Phone Number</b></label>
  <input type="tel" class="form-control" style="width:100%; border:1px solid black" id="phone" name="phone" maxlength="10" placeholder="(+91)...">
</div>
<div class="mb-3">
  <label for="desc" class="form-label"><b>Your Description</b></label>
  <textarea class="form-control" id="desc" style="width:100%; border:1px solid black" rows="3" name="desc" placeholder="Type message in 500 words..."></textarea>
</div>
        <div class="text-center">
    <button class="btn btn-primary" type="submit" > Submit </button>
            </div>
</form>
  </div>
    </div>
</div>
{% endblock content %}


{% block title %}
Contact
{% endblock title %}

templates/index.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

<div class="container-fluid " >
<div id="carouselExampleCaptions" class="carousel slide" >
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>

  <div class="carousel-inner my-2">
    <div class="carousel-item active" >
      <a href="{% static '/img/1.jfif' %}">
      <center><img src="{% static '/img/1.jfif' %}" class="d-block w-100" alt="..." width="1300" height="500"></center>
      </a>
        <div class="carousel-caption d-none d-md-block">
        <h5>Walnut Chocolate Cone</h5>
        <p class="h6 d-inline p-2" style="background: green; border-radius:63px">chew it, lick it, taste it, swallow it .</p>
      </div>
    </div>
    <div class="carousel-item">
      <a href="{% static '/img/2.jfif' %}">
      <img src="{% static '/img/2.jfif' %}" class="d-block w-100" alt="..." width="1300" height="500">
      </a>
        <div class="carousel-caption d-none d-md-block " >
        <h5>Have some CupCakes...</h5>
        <p class="h6 d-inline p-2 " style="background: green; border-radius:63px">Serve as Dessert </p>
      </div>
    </div>
    <div class="carousel-item">
      <a href="/static/img/3.jfif">
      <img src="/static/img/3.jfif" class="d-block w-100" alt="..." width="1300" height="500">
      </a>
        <div class="carousel-caption d-none d-md-block p-2 bg-black bg-opacity-50 "  style=" border-radius:53px"  >
        <h5>Butterscotch, Chocolate, Vanilla...</h5>
        <p>Different flavours for different people</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="false"></span>
    <span style="color:light"><b>Previous</b></span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="false"></span>
    <span style="color:light"><b>Next</b></span>
  </button>
</div>
</div>

    {% if name %}  <!-- if name parameter is given in views.py request then print this -->
    <h1 class="my-4 text-center" style="font-family:Chaparral Pro Light;">Hello {{ name }}, Choose from our store of Ice Creams</h1>
    {% else %}
    <h1 class="my-4 text-center" style="font-family:Chaparral Pro Light;"> Hello Customer, Choose from our store of Ice Creams</h1>
    {% endif %}

<div class="container">
  <div class="row row-cols-1 mb-5 row-cols-sm-2 row-cols-md-3 g-3">


        {% for dtl in dtls %}
        <div class="col" >
          <div class="card shadow-sm" style="width:100%; height:100%">
           <img src="{{dtl.img.url}}" style="width:100%; height:100%" >
            <div class="card-body">
              <p class="card-text" style="font-size: 20px"><b>{{dtl.name}} </b> </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
<!-- Relative Url -->
                  <button type="button" class="btn btn-sm btn-outline-secondary" onclick="window.location.href = '{% url 'app1:Ice_cream_details' dtl.icecream_slug %}'">View</button>
<!-- <button type="button" class="btn btn-sm btn-outline-secondary">Buy</button> -->
                </div>
                <small class="text-body-secondary" style="font-size: 18px" >₹{{dtl.price}}/- full pack</small>
              </div>
            </div>
          </div>
        </div>
        
<!-- If there is no data in record -->
        {% empty %}
        <div class="container my-3" style="text-align: center">
        <h2>  No IceCream Found </h2>
        </div>

        {% endfor %}
  
      </div>

      {% if request.COOKIES.recent_items %}
      <div class='title mb-5' >  Recent Items -
      {{ request.COOKIES.recent_items }}
    </div>
      {% endif %}

</div>


{% endblock content %}


{% block title %}
IceCreams
{% endblock title %}

templates/login.html
{% extends 'base.html' %}

{% block content %}

{% load static %}
    <link rel="stylesheet" type="text/css" href="/static/css/sign-in.css">
<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->

    <!-- Icon -->
    <div class="fadeIn first">
      <img src="/static/img/profile_icon.svg" width="10px" height="100px" id="icon" alt="User Icon" />
    </div>

    <!-- Login Form -->
    <form  method="post" action="/users/login/">
          {% csrf_token %}

      <input type="text" class="fadeIn second" id="login" name="Username" placeholder="Enter your name" required>
      <input type="password" class="fadeIn third" id="password" name="Password" placeholder="Password" required>
      <input type="submit" class="fadeIn fourth" value="Log In">
    </form>


    <!-- Remind Passowrd -->
    <div id="formFooter">
      <div class="d-flex justify-content-center links">
        Don't have an account?  <a class="underlineHover" href="/users/register">Sign Up</a>
      </div>
      <a class="underlineHover" href="{% url 'reset-password' %}">Forgot Password?</a>
      <p class="text-body-secondary">&copy; 2017–2023</p>
    </div>

  </div>
</div>

{% endblock content %}


{% block title %}
Login
{% endblock title %}

templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logged Out</title>
</head>
<body>
<p> You have logged out successfully.</p>
<a href="/login"> Login again </a>
</body>
</html>

templates/register.html
{% extends 'base.html' %}

{% block content %}
<link rel='stylesheet' type='text/css' href='/static/css/register.css'>
<section class=" bg-image"
  style="background-image: url('https://mdbcdn.b-cdn.net/img/Photos/new-templates/search-box/img4.webp');">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">Create an account</h2>

              <form method="post", action=''>
                {% csrf_token %}
                <div class="row">
                    <div class="col ">
                        <div class="form-outline mb-2">
                        <label class="form-label" for="form3Examplev2">First name</label>
                        <input type="text" name="fname" id="form3Examplev2" class="form-control form-control-lg" required/>
                        </div>
                      </div>
                    <div class="col">
                        <div class="form-outline mb-2">
                        <label class="form-label" for="form3Examplev3">Last name</label>
                        <input type="text" name='lname' id="form3Examplev3" class="form-control form-control-lg" required/>
                        </div>
                    </div>
                </div>

                <div class="form-outline mb-2">
                    <label class="form-label" for="form3Example3cg">Username</label>
                  <input type="text" name='uname' id="form3Example3cg" class="form-control form-control-lg" required/>
                </div>

                <div class="form-outline mb-2">
                    <label class="form-label" for="form3Example3cg">Your Email</label>
                  <input type="email" name='email' id="form3Example3cg" class="form-control form-control-lg" required/>
                </div>

                <div class="form-outline mb-2">
                    <label class="form-label" for="form3Example4cg">Password</label>
                  <input type="password" name='password1' id="form3Example4cg" class="form-control form-control-lg" required/>
                </div>

                <div class="form-outline mb-2">
                    <label class="form-label" for="form3Example4cdg">Repeat your password</label>
                  <input type="password" name='password2' id="form3Example4cdg" class="form-control form-control-lg" required/>
                </div>

                <div class="form-check d-flex justify-content-center mb-3">
                  <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3cg" required/>
                  <label class="form-check-label" for="form2Example3g">
                    I agree all statements in <a href="#!" class="text-body"><u>Terms of service</u></a>
                  </label>
                </div>

                <div class="d-flex justify-content-center">
                  <button type="submit"
                    class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">Register</button>
                </div>

                <p class="text-center text-muted mt-3 mb-0">Have already an account? <a href="/users/login"
                    class="fw-bold text-body"><u>Login here</u></a></p>

              </form>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


{% endblock content %}

{% block title %}
Registration Form
{% endblock title %}

templates/services.html
{% extends 'base.html' %}

{% block content %}

{% load static %}
<link rel='stylesheet' type='text/css' href='{% static '/css/services.css' %}'>
<div class="container py-5">

    <!-- For demo purpose -->
    <div class="row text-center text-white mb-5">
      <div class="col-lg-7 mx-auto">
        <h1 class="display-4">Choose The Flavor</h1>
      </div>
    </div>
    <!-- End -->
  
    <div class="row">
      <div class="col-lg-8 mx-auto">
  
        <!-- List group-->
        <ul class="list-group shadow">
          {% for dtl in dtls %}
          <!-- list group item-->
          <li class="list-group-item">
            <!-- Custom content-->
            <div class="media align-items-lg-center flex-column flex-lg-row p-3">
              <div class="media-body order-2 order-lg-1">
              
<!-- standard way to call dynamic url -->
              <!--  <a href='/icd/{{dtl.icecream_slug}}'>  -->
<!-- Relative way to call dynamic url-->
                <a href = "{% url 'app1:Ice_cream_details' dtl.icecream_slug %}">
                <h5 class="mt-0 font-weight-bold mb-2">{{dtl.name}}</h5></a>
                <p class="font-italic text-muted mb-0 small">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit fuga autem maiores necessitatibus.</p>
                <div class="d-flex align-items-center justify-content-between mt-1">
                  <h6 class="font-weight-bold my-2">₹{{dtl.price}}</h6>
                  <ul class="list-inline small">
                    <li class="list-inline-item m-0"><i class="fa fa-star text-success"></i></li>
                    <li class="list-inline-item m-0"><i class="fa fa-star text-success"></i></li>
                    <li class="list-inline-item m-0"><i class="fa fa-star text-success"></i></li>
                    <li class="list-inline-item m-0"><i class="fa fa-star text-success"></i></li>
                    <li class="list-inline-item m-0"><i class="fa fa-star-o text-gray"></i></li>
                  </ul>
                </div>
              </div><img src="{{dtl.img.url}}" alt="Generic placeholder image" width="200" class="ml-lg-5 order-1 order-lg-2">
            </div>
            <!-- End -->
          </li>
          <!-- End -->
          {% endfor %}
  
        </ul>
        <!-- End -->
      </div>
    </div>
  </div>


{% endblock content %}


{% block title %}
Services
{% endblock title %}